# Generated by Django 6.0.3 on 2026-06-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issuing_organization', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='certificates/')),
                ('image_url', models.URLField(blank=True, help_text='Optional external image URL if not uploading file', max_length=500, null=True)),
                ('verification_link', models.URLField(blank=True, null=True)),
                ('date_issued', models.CharField(help_text='e.g., Dec 2025', max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=150)),
                ('company', models.CharField(max_length=150)),
                ('location', models.CharField(blank=True, max_length=150, null=True)),
                ('duration', models.CharField(help_text='e.g., June 2025 - Present', max_length=100)),
                ('responsibilities', models.TextField(help_text='Enter responsibilities, one per line or separated by double newlines')),
                ('order', models.IntegerField(default=0, help_text='Ordering key (smaller values show first)')),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('image_url', models.URLField(blank=True, help_text='Optional external image URL if not uploading file', max_length=500, null=True)),
                ('technologies', models.CharField(help_text='Comma-separated values, e.g. React, Django, PostgreSQL', max_length=255)),
                ('live_link', models.URLField(blank=True, null=True)),
                ('github_link', models.URLField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('database', 'Database'), ('mobile', 'Mobile'), ('tools', 'Tools')], max_length=20)),
                ('proficiency', models.IntegerField(default=100, help_text='Enter proficiency as a percentage (e.g., 85)')),
                ('order', models.IntegerField(default=0, help_text='Ordering key for listing')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
